services:
  csi-survey:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - docker.env
    environment:
      - NODE_ENV=production
      - PORT=5000
      - CORS_ORIGIN=http://localhost:5000
    restart: unless-stopped
